# Setup
name: SunSPEC 6 team's blog
tagline: A blog site created and maintained by FYP Team 2018-2019
baseurl: ""
locale: "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-architect